title: Lei Zhang
description: "We shape AI, and AI is shaping us back."
url: "https://resouer.github.io"

theme: minima

minima:
  skin: classic
  date_format: "%b %-d, %Y"
  social_links:
    github: resouer
    twitter: resouer
    linkedin: harry-lei-zhang

header_pages:
  - blog.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

show_excerpts: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
